### ISSUE TITLE
Data set with a period & using multiprocess nose

### ISSUE THREAD

**Issue by darrenmoen** [box/genty#41]
I have a data set that contains a period (specifically an IP address) and when I use Genty with multiprocessed nose, I'm getting an error.

Running as a normal unit test through an IDE works fine.
If the data does not contain a period, or nose is not run with multi-processes, it works fine too.

Sample class and nose command below.

Any help would be appreciated.

```
import unittest
from genty import genty, genty_dataset

@genty
class TestGentyWithNose(unittest.TestCase):
    _multiprocess_can_split_ = True

    @genty_dataset('127.0.0.1', '192.168.1.1')
    def test_method(self, arg):
        print arg
```

From nose using:
```
nosetests --processes=4 test_genty_with_nose.py
```

Error: Failure: ValueError (No such test TestGentyWithNose.test_method('192.168.1.1'))
----------------------------------------------------------------------
Traceback (most recent call last):
  File "~/.virtualenvs/automation/lib/python2.7/site-packages/nose-1.3.4-py2.7.egg/nose/failure.py", line 42, in runTest
    raise self.exc_class(self.exc_val)
ValueError: No such test TestGentyWithNose.test_method('192.168.1.1')

**Comment by potrebic** [comment]
Hi Darren,

I didn't have the time to invest this today. I'll try tomorrow. I bet using named-parameters would work around the issue

```
@genty_dataset(
     addr1='127.0.0.1',
     addr2='192.168.1.1',
)
```

I hope that gets you going.

Peter

**Comment by potrebic** [comment]
Looks like in the named-param case you have to explicitly make the param-values a tuple:


```
@genty_dataset(
     addr1=('127.0.0.1',),
     addr2=('192.168.1.1',),
)
```

I can look into that as well. I know that there is special logic involve in the non-named-param case because gently expects to iterate over data-sets and parameters in each data-set. And a 'string' iterable... so it can confuse things.

**Comment by potrebic** [comment]
So I poked around some. The issue is that the multiprocessing code ends up calling nose's "loader" code with data as if one was specifying a specific test method on the command line. Something like:
```
nosetests <path>/test_example.py:ExampleTests.test_method(u\\'127.0.0.1\\')
```
And nose's loader will parse that string, splitting on '.' looking for the final test. And of course things get all confused and the test isn't found.

I don't immediately see any easy options. Gently could stop placing '.' in function names. That would ruin the elegance of the names. Could make that optional, with gently perhaps sniffing some ENV variable.

**Comment by darrenmoen** [comment]
Peter,
thanks for your replies.
Most of our tests have dynamically generated data, using @genty_dataprovider and @genty_dataset together. 
Is it possible to name parameters using that pattern? The example I gave was just for simplicity.

Yeah, replacing (preferably, maybe with a space?) or removing (def. makes the names less readable) the '.' seems like an simple fix. 
It's possible there are other characters too, that nose, or another test runner, doesn't like.

**Comment by darrenmoen** [comment]
I managed to find a workaround by wrapping the ip address inside a class, and providing a __repr__ for the class:

```
import unittest
from genty import genty, genty_dataset

class IpAddress(object):
    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return self.value.replace('.', ' ')

@genty
class TestGentyWithNose(unittest.TestCase):
    _multiprocess_can_split_ = True

    def setUp(self):
        print('Running test {0}'.format(self._testMethodName))

    @genty_dataset(IpAddress('127.0.0.1'), IpAddress('192.168.1.1'))
    def test_method(self, arg):
        print arg.value
```

The method name ends up with a space, and nose is happy:
```
Running test test_method(127 0 0 1)
127.0.0.1
Running test test_method(192 168 1 1)
192.168.1.1
```
